services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mlapi
    environment:
      - MONGO_URI=<''>
    restart: always

  mlapi:
    build: ./ML-API
    ports:
      - "5001:5001"
    restart: always

